# Generated by Django 4.1 on 2022-08-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventos_usuario_alter_eventos_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='habilitado',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
