# Generated by Django 4.1 on 2022-08-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0004_alter_plan_icone_alter_resource_icone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speech',
            old_name='menssagem',
            new_name='mensagem',
        ),
    ]
