# Generated by Django 4.1 on 2022-08-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0005_rename_menssagem_speech_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='speech/'),
        ),
    ]
