# Generated by Django 4.1 on 2022-08-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0008_speech_imagem_alter_team_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
