# Generated by Django 4.1 on 2022-08-29 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0009_alter_contact_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='fusion.empresa'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='fusion.empresa'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='fusion.empresa'),
        ),
        migrations.AlterField(
            model_name='service',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='fusion.empresa'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speechs', to='fusion.empresa'),
        ),
        migrations.AlterField(
            model_name='team',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='fusion.empresa'),
        ),
    ]
