# Generated by Django 4.1 on 2022-08-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0012_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
