# Generated by Django 4.1 on 2022-09-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0014_team_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='experiencia',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
