# Generated by Django 4.1 on 2022-09-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0016_service_liberado_alter_service_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('deleted', 'Deletado'), ('blocked', 'Bloqueado')], default='active', max_length=11, verbose_name='Status'),
        ),
    ]
