# Generated by Django 4.1 on 2022-09-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0017_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Ativo'), ('deleted', 'Deletado'), ('blocked', 'Bloqueado')], default='active', max_length=11, null=True, verbose_name='Status'),
        ),
    ]
